/**
 * PDF HTML Forge - HTML Export Logic
 * 
 * This module handles the creation of HTML, CSS, and ZIP exports from converted PDF pages.
 * It generates static, offline-capable HTML with strict CSP.
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { 
  ConversionMode, 
  RenderScale, 
  PageAsset, 
  ExportResult,
  Metadata,
  PdfDocumentInfo,
} from '../types';
import { escapeHtml, escapeHtmlAttribute } from './escapeHtml';
import { formatFileSize } from './fileSize';

/**
 * HTML export configuration
 */
export interface HtmlExportConfig {
  mode: ConversionMode;
  scale: RenderScale;
  includeTextLayer: boolean;
  includeOriginalPdf: boolean;
  originalPdf?: File;
}

/**
 * Default HTML export configuration
 */
export const DEFAULT_EXPORT_CONFIG: HtmlExportConfig = {
  mode: 'visual',
  scale: 2,
  includeTextLayer: true,
  includeOriginalPdf: false,
};

/**
 * Generate a complete HTML export from page assets
 * @param pageAssets - The page assets to export
 * @param documentInfo - The PDF document information
 * @param config - The export configuration
 * @returns Promise that resolves to the export result
 */
export async function generateHtmlExport(
  pageAssets: PageAsset[],
  documentInfo: PdfDocumentInfo,
  config: HtmlExportConfig
): Promise<ExportResult> {
  // Create ZIP archive
  const zip = new JSZip();
  
  // Generate metadata
  const metadata = generateMetadata(pageAssets, documentInfo, config);
  
  // Add metadata to ZIP
  zip.file('metadata.json', JSON.stringify(metadata, null, 2));
  
  // Generate CSS
  const cssContent = generateCss(pageAssets, config);
  zip.file('styles.css', cssContent);
  
  // Generate HTML
  const htmlContent = generateHtml(pageAssets, documentInfo, config);
  zip.file('index.html', htmlContent);
  
  // Add page assets (images)
  const assetsFolder = zip.folder('assets');
  if (assetsFolder) {
    for (const pageAsset of pageAssets) {
      const pageNumberStr = String(pageAsset.pageNumber).padStart(3, '0');
      const fileName = `page-${pageNumberStr}.png`;
      
      // Revoke the object URL after adding to ZIP
      assetsFolder.file(fileName, pageAsset.imageBlob, { binary: true });
      URL.revokeObjectURL(pageAsset.imageUrl);
    }
  }
  
  // Add original PDF if requested
  if (config.includeOriginalPdf && config.originalPdf) {
    zip.file(config.originalPdf.name, config.originalPdf, { binary: true });
  }
  
  // Generate ZIP
  const zipBlob = await zip.generateAsync({ type: 'blob' });
  
  // Generate export filename
  const baseName = sanitizeFileName(documentInfo.fileName);
  const fileName = `${baseName.replace(/\.pdf$/i, '')}-html-export.zip`;
  
  return {
    zipBlob,
    fileName,
  };
}

/**
 * Generate HTML content for the export
 * @param pageAssets - The page assets
 * @param documentInfo - The PDF document information
 * @param config - The export configuration
 * @returns The HTML content as a string
 */
function generateHtml(
  pageAssets: PageAsset[],
  documentInfo: PdfDocumentInfo,
  config: HtmlExportConfig
): string {
  const baseName = sanitizeFileName(documentInfo.fileName);
  const title = escapeHtml(baseName.replace(/\.pdf$/i, ''));
  
  // Generate page HTML based on mode
  const pagesHtml = generatePagesHtml(pageAssets, config);
  
  // Generate metadata for HTML head
  const metaTags = generateMetaTags(title, documentInfo);
  
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  ${metaTags}
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="document-container">
    <header class="document-header">
      <h1>${title}</h1>
      <p class="document-info">
        <span>${pageAssets.length} page(s)</span> | 
        <span>${formatFileSize(documentInfo.fileSize)}</span>
      </p>
    </header>
    
    <main class="document-content">
      ${pagesHtml}
    </main>
    
    <footer class="document-footer">
      <p>Generated by PDF HTML Forge | ${new Date().toISOString().split('T')[0]}</p>
    </footer>
  </div>
  
  <script>
    // Print styles
    function setupPrintStyles() {
      const style = document.createElement('style');
      style.media = 'print';
      style.textContent = 
        '.page { box-shadow: none !important; } ' +
        '.page img { max-width: 100% !important; height: auto !important; }';
      document.head.appendChild(style);
    }
    
    // Helper to toggle text overlay visibility for debugging/accessibility
    window.toggleTextOverlay = function(show) {
      document.querySelectorAll('.text-layer :is(span, br)').forEach(el => {
        el.style.color = show ? 'rgba(0,0,0,0.6)' : 'transparent';
      });
    };
    
    // Initialize
    document.addEventListener('DOMContentLoaded', setupPrintStyles);
  </script>
</body>
</html>`;

  return html;
}

/**
 * Generate CSS content for the export
 * @param pageAssets - The page assets
 * @param config - The export configuration
 * @returns The CSS content as a string
 */
function generateCss(pageAssets: PageAsset[], config: HtmlExportConfig): string {
  // Calculate aspect ratios for each page
  const pageStyles = pageAssets.map(asset => {
    const aspectRatio = asset.width / asset.height;
    return `
      .page-${asset.pageNumber} {
        width: ${asset.width}px;
        max-width: 100%;
        height: auto;
        aspect-ratio: ${aspectRatio};
      }
      
      .page-${asset.pageNumber} img {
        width: 100%;
        height: auto;
        display: block;
      }
    `;
  }).join('\n');

  const css = `/*
 * PDF HTML Forge - Generated Styles
 * Mode: ${config.mode}
 * Scale: ${config.scale}x
 * Generated: ${new Date().toISOString()}
 */

/* Reset and base styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  height: 100%;
  background-color: #1a1a2e;
  color: #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
}

/* Document container */
.document-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  padding: 2rem;
  max-width: 1400px;
  margin: 0 auto;
}

/* Document header */
.document-header {
  text-align: center;
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid #333;
}

.document-header h1 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
  color: #fff;
}

.document-info {
  color: #888;
  font-size: 0.9rem;
}

/* Document content */
.document-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  align-items: center;
}

/* Page styles */
.page {
  background: white;
  border-radius: 8px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
  overflow: hidden;
  position: relative;
  max-width: 100%;
}

.page img {
  display: block;
  width: 100%;
  height: auto;
}

/* Text layer for visual mode */
${config.includeTextLayer && config.mode === 'visual' ? `
.text-layer-svg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  z-index: 2;
}

.text-layer {
  position: absolute;
  text-align: initial;
  inset: 0;
  overflow: clip;
  opacity: 1;
  line-height: 1;
  -webkit-text-size-adjust: none;
  -moz-text-size-adjust: none;
  text-size-adjust: none;
  forced-color-adjust: none;
  transform-origin: 0 0;
}

.text-layer :is(span,br) {
  color: transparent;
  position: absolute;
  white-space: pre;
  cursor: text;
  transform-origin: 0% 0%;
  pointer-events: auto;
}

.text-layer ::selection {
  background: rgba(255, 235, 59, 0.9);
  color: #000;
}

.text-layer ::-moz-selection {
  background: rgba(255, 235, 59, 0.9);
  color: #000;
}

.text-layer-content {
  position: absolute;
  color: transparent;
  white-space: pre-wrap;
  word-wrap: break-word;
  font-size: 12px;
  line-height: 1.4;
  text-shadow: 0 0 0 transparent;
}
` : ''}

/* Individual page styles */
${pageStyles}

/* Document footer */
.document-footer {
  text-align: center;
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid #333;
  color: #666;
  font-size: 0.8rem;
}

/* Responsive styles */
@media (max-width: 768px) {
  .document-container {
    padding: 1rem;
  }
  
  .page {
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
  }
}

/* Print styles */
@media print {
  body {
    background: white;
    color: black;
  }
  
  .document-container {
    padding: 0;
    max-width: none;
  }
  
  .document-header,
  .document-footer {
    display: none;
  }
  
  .page {
    box-shadow: none;
    break-inside: avoid;
    margin-bottom: 1cm;
  }
}
`;

  return css;
}

/**
 * Generate HTML for individual pages
 * @param pageAssets - The page assets
 * @param config - The export configuration
 * @returns HTML string for all pages
 */
function generatePagesHtml(pageAssets: PageAsset[], config: HtmlExportConfig): string {
  return pageAssets.map(asset => {
    const pageNumberStr = String(asset.pageNumber).padStart(3, '0');
    const imageFileName = `assets/page-${pageNumberStr}.png`;
    
    if (config.mode === 'visual') {
      // Visual fidelity mode: image with optional text layer
      let textLayerHtml = '';
      
      if (config.includeTextLayer) {
        if (asset.textLayerHtml) {
          // Visual text layer using SVG foreignObject scaling for pixel-perfect positioning
          textLayerHtml = `
        <svg class="text-layer-svg" viewBox="0 0 ${asset.width} ${asset.height}">
          <foreignObject x="0" y="0" width="${asset.width}" height="${asset.height}">
            <div xmlns="http://www.w3.org/1999/xhtml" class="text-layer" style="width: ${asset.width}px; height: ${asset.height}px;">
              ${asset.textLayerHtml}
            </div>
          </foreignObject>
        </svg>
          `;
        } else if (asset.textContent) {
          // Fallback text layer
          const escapedContent = asset.textContent.split('\n').map(line => escapeHtml(line)).join('\n');
          textLayerHtml = `
        <div class="text-layer">
          <div class="text-layer-content">
            ${escapedContent}
          </div>
        </div>
          `;
        }
      }
      
      return `
        <div class="page page-${asset.pageNumber}" id="page-${asset.pageNumber}">
          <img src="${escapeHtmlAttribute(imageFileName)}" alt="Page ${asset.pageNumber}" />
          ${textLayerHtml}
        </div>
      `;
    } else {
      // Structured mode: semantic-ish HTML
      return generateStructuredPageHtml(asset);
    }
  }).join('\n');
}

/**
 * Generate structured HTML for a page (experimental mode)
 * @param asset - The page asset
 * @param pageNumberStr - The page number as a string
 * @returns HTML string for the structured page
 */
function generateStructuredPageHtml(asset: PageAsset): string {
  const textContent = asset.textContent || '';
  
  // Split by paragraph breaks and wrap in <p> tags
  const paragraphs = textContent.split(/\n\n+/).map(para => {
    const escapedPara = escapeHtml(para).replace(/\n/g, '<br>');
    return `<p>${escapedPara}</p>`;
  }).join('\n');
  
  return `
    <article class="page page-${asset.pageNumber}" id="page-${asset.pageNumber}">
      <header class="page-header">
        <h2>Page ${asset.pageNumber}</h2>
      </header>
      <div class="page-content">
        <div class="page-text">
          ${paragraphs}
        </div>
      </div>
      <footer class="page-footer">
        <p>Page ${asset.pageNumber}</p>
      </footer>
    </article>
  `;
}

/**
 * Generate metadata for the HTML head section
 * @param title - The document title
 * @param documentInfo - The PDF document information
 * @param config - The export configuration
 * @returns HTML meta tags string
 */
function generateMetaTags(
  title: string,
  documentInfo: PdfDocumentInfo
): string {
  const description = escapeHtmlAttribute(
    `HTML export of ${documentInfo.fileName} - ${documentInfo.numPages} pages`
  );
  
  // Strict CSP as required
  const csp = `default-src 'none'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:`;
  
  return `
    <meta name="description" content="${description}">
    <meta name="author" content="PDF HTML Forge">
    <meta name="generator" content="PDF HTML Forge v1.0.0">
    <meta name="robots" content="noindex, nofollow">
    <meta http-equiv="Content-Security-Policy" content="${csp}">
    <meta name="theme-color" content="#1a1a2e">
    <meta property="og:title" content="${title}">
    <meta property="og:description" content="${description}">
    <meta property="og:type" content="website">
  `;
}

/**
 * Generate metadata JSON for the export
 * @param pageAssets - The page assets
 * @param documentInfo - The PDF document information
 * @param config - The export configuration
 * @returns Metadata object
 */
function generateMetadata(
  pageAssets: PageAsset[],
  documentInfo: PdfDocumentInfo,
  config: HtmlExportConfig
): Metadata {
  return {
    title: sanitizeFileName(documentInfo.fileName).replace(/\.pdf$/i, ''),
    author: '',
    subject: `HTML export of ${documentInfo.fileName}`,
    keywords: 'pdf, html, export, conversion',
    creator: 'PDF HTML Forge',
    producer: 'PDF HTML Forge v1.0.0',
    creationDate: new Date().toISOString(),
    modificationDate: new Date().toISOString(),
    numPages: pageAssets.length,
    fileName: documentInfo.fileName,
    fileSize: documentInfo.fileSize,
    exportDate: new Date().toISOString(),
    mode: config.mode,
    scale: config.scale,
  };
}

/**
 * Sanitize a filename for use in URLs and file systems
 * @param fileName - The filename to sanitize
 * @returns Sanitized filename
 */
function sanitizeFileName(fileName: string): string {
  return fileName
    .replace(/[^a-zA-Z0-9._-]/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-+/g, '-')
    .substring(0, 100);
}

/**
 * Download the export ZIP file
 * @param exportResult - The export result
 */
export function downloadExport(exportResult: ExportResult): void {
  saveAs(exportResult.zipBlob, exportResult.fileName);
}

/**
 * Revoke all object URLs from page assets
 * @param pageAssets - The page assets
 */
export function revokePageAssetUrls(pageAssets: PageAsset[]): void {
  for (const asset of pageAssets) {
    if (asset.imageUrl) {
      URL.revokeObjectURL(asset.imageUrl);
    }
  }
}

/**
 * Clean up resources after export
 * @param pageAssets - The page assets to clean up
 */
export function cleanupExportResources(pageAssets: PageAsset[]): void {
  // Revoke all object URLs
  revokePageAssetUrls(pageAssets);
}

export default {
  generateHtmlExport,
  generateHtml,
  generateCss,
  generatePagesHtml,
  generateMetadata,
  downloadExport,
  revokePageAssetUrls,
  cleanupExportResources,
};
